### ISSUE TITLE
Failed to connect: aws-c-common: AWS_ERROR_SYS_CALL_FAILURE

### ISSUE THREAD

**Issue by monelgordillo** [aws/aws-iot-device-sdk-js-v2#308]
### Describe the bug

I am trying to connect a device to AWS IoT.  I'm using the given start.sh.  

![image](https://user-images.githubusercontent.com/36521543/207364493-1f0ce01c-20ee-436f-a059-5f6dd922f0f5.png)

start.sh seems to do a following:

```
curl https://www.amazontrust.com/repository/AmazonRootCA1.pem > root-CA.crt
git clone https://github.com/aws/aws-iot-device-sdk-js-v2.git --recursive
npm install
cd samples/node/pub_sub
npm install
```

then...

`node aws-iot-device-sdk-js-v2/samples/node/pub_sub/dist/index.js --endpoint a1x8uwz4upqdhk-ats.iot.us-east-1.amazonaws.com --key DEVICE.private.key --cert DEVICE.cert.pem --ca_file root-CA.crt --client_id sdk-nodejs-v2 --topic topic_1`

However, on the node command, I am getting this error message:

`Failed to connect: aws-c-common: AWS_ERROR_SYS_CALL_FAILURE, System call failure`

### Expected Behavior

I expect to see messages showing up in AWS Console in the previous screenshot.

### Current Behavior

I'm getting:

Failed to connect: aws-c-common: AWS_ERROR_SYS_CALL_FAILURE, System call failure

### Reproduction Steps

Follow the AWS IoT wizard to connect a device, then download & execute start.sh.

### SDK version used

v1.9.0

### Environment details (OS name and version, etc.)

Linux ARM architecture

**Comment by jmklix** [comment]
Can you provide more details about what device that you are running it on and include more detailed logs?

I'm able to run the sample without any errors, but I did notice that the sample is publishing to `topic_1` while the webpage is subscribed to `topic_2`. This shouldn't have cause the error that you are seeing, but I did want to note it. Also it should be fixed now.

**Comment by monelgordillo** [comment]
A couple of things on that start.sh script that I noticed:

cd samples/node/pub_sub -> cd samples/node/pub_sub_js
node aws-iot-device-sdk-js-v2/samples/node/pub_sub/dist/index.js -> node aws-iot-device-sdk-js-v2/samples/node/pub_sub_js/index.js
--ca_file -> --root-ca
topic_1 -> topic_2

I'm still getting the same error unfortunately:

Failed to connect: aws-c-common: AWS_ERROR_SYS_CALL_FAILURE, System call failur

The device is linux 3.10.49 arm7l.

How can I enable more logging on aws-iot-device-sdk-js-v2?  

Thank you

**Comment by jmklix** [comment]
[Enable Logging:](https://github.com/aws/aws-iot-device-sdk-js-v2/blob/main/documents/FAQ.md#how-do-i-enable-logging)
```js
const level = parseInt(io.LogLevel["ERROR"]);
io.enable_logging(level);
```

**Comment by monelgordillo** [comment]
I'm a nodejs noob.  I'm getting:

ReferenceError: io is not defined

**Comment by jmklix** [comment]
Make sure you have `import {io} from 'aws-iot-device-sdk-v2';` to the top of the file
